version: '3.9'

services:
    database:
        image: postgres
        container_name: amazon-1
        restart: always
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=core
        volumes:
            - pgdata:/data/postgres

    redis:
        image: redis:alpine
        container_name: cache
        restart: always
        ports:
            - 6379:6379

volumes:
    pgdata:
        driver: local
